spring.application.name=springweb_mvc


spring.mvc.view.prefix= /views/

spring.mvc.view.suffix=  .jsp


# A DataSource is a factory for connections to the physical databases. It uses a Driver class name, URL, username, and password to establish the database connection.
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/emp_db
spring.datasource.username = root
spring.datasource.password = admin


